
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



public class BilgiEkrani extends javax.swing.JDialog {
    DefaultTableModel model;
    OgrenciIslemleri islemler =  new OgrenciIslemleri();
   
       /**
     * Creates new form DersProgramiEkrani
     */
    public BilgiEkrani(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
        initComponents();
        model = (DefaultTableModel) bilgi_tablo.getModel();
      
       
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bilgi_tablo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bilgiler_alani = new javax.swing.JTextField();
        bilgi = new javax.swing.JButton();
        maxlab = new javax.swing.JLabel();
        minlab = new javax.swing.JLabel();
        maxnot = new javax.swing.JButton();
        minbutton = new javax.swing.JButton();
        ortnot = new javax.swing.JButton();
        ortlab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DERS PROGRAMI EKRANI");

        bilgi_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no", "ad", "soyad", "kredi", "gpa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bilgi_tablo);
        if (bilgi_tablo.getColumnModel().getColumnCount() > 0) {
            bilgi_tablo.getColumnModel().getColumn(0).setResizable(false);
            bilgi_tablo.getColumnModel().getColumn(1).setResizable(false);
            bilgi_tablo.getColumnModel().getColumn(2).setResizable(false);
            bilgi_tablo.getColumnModel().getColumn(3).setResizable(false);
            bilgi_tablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Ogrenci No:");

        bilgi.setText("Bilgiler");
        bilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiActionPerformed(evt);
            }
        });

        maxlab.setText("maximum");

        minlab.setText("minumum");

        maxnot.setText("Maximum not");
        maxnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxnotActionPerformed(evt);
            }
        });

        minbutton.setText("minumum not");
        minbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbuttonActionPerformed(evt);
            }
        });

        ortnot.setText("Sınıf Ortalması");
        ortnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortnotActionPerformed(evt);
            }
        });

        ortlab.setText("ortalama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(minlab)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(maxlab)
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(bilgi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bilgiler_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ortlab)
                                        .addGap(25, 25, 25))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(561, 561, 561)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minbutton)
                                    .addComponent(maxnot))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ortnot)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(maxnot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(ortnot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bilgiler_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ortlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bilgi)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void bilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiActionPerformed
       
        try {
             Ogrenci ogrenci =islemler.ogrencileriBul(Integer.parseInt(bilgiler_alani.getText()));
             if(ogrenci!=null){
             Object[] eklenecek = {ogrenci.getNo(),ogrenci.getAd(),ogrenci.getSoyad(),ogrenci.getKredi(),ogrenci.getGpa()};
             model.addRow(eklenecek);}
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BilgiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_bilgiActionPerformed

    private void maxnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxnotActionPerformed
        try {
            maxlab.setText(String.valueOf(islemler.maxnot()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BilgiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maxnotActionPerformed

    private void minbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbuttonActionPerformed
        try {
            minlab.setText(String.valueOf(islemler.minnot()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BilgiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_minbuttonActionPerformed

    private void ortnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortnotActionPerformed
         try {
            ortlab.setText(String.valueOf(islemler.ortnot()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BilgiEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ortnotActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilgiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilgiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilgiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilgiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BilgiEkrani dialog = new BilgiEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgi;
    private javax.swing.JTable bilgi_tablo;
    private javax.swing.JTextField bilgiler_alani;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxlab;
    private javax.swing.JButton maxnot;
    private javax.swing.JButton minbutton;
    private javax.swing.JLabel minlab;
    private javax.swing.JLabel ortlab;
    private javax.swing.JButton ortnot;
    // End of variables declaration//GEN-END:variables
}
